-- =============================================
-- Customer Behavior Analysis Queries
-- Database: PostgreSQL
-- =============================================

-- Q1: Total revenue generated by male vs female customers
SELECT gender,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;


-- Q2: Customers who used a discount but spent more than the average purchase amount
SELECT customer_id,
       purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );


-- Q3: Top 5 products with the highest average review rating
SELECT item_purchased,
       ROUND(AVG(review_rating::NUMERIC), 2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4: Compare average purchase amounts between Standard and Express Shipping
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5: Compare spend and revenue between subscribers and non-subscribers
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS average_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6: Top 5 products with highest percentage of discounted purchases
SELECT item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7: Segment customers into New, Returning, and Loyal
WITH customer_segments AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'NEW'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
               ELSE 'LOYAL'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_segments
GROUP BY customer_segment;


-- Q8: Top 3 most purchased products within each category
WITH ranked_items AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT category,
       item_purchased,
       total_orders,
       item_rank
FROM ranked_items
WHERE item_rank <= 3
ORDER BY category, item_rank;


-- Q9: Subscription likelihood among repeat buyers (previous_purchases > 5)
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10: Revenue contribution of each age group
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

